// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.client.testapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;
import java.util.concurrent.CompletableFuture;

@Servant
public interface HelloPrx {

	 String hello(int no, String name);

	CompletableFuture<String>  promise_hello(int no, String name);

	 String hello(int no, String name, @TarsContext java.util.Map<String, String> ctx);

	 void async_hello(@TarsCallback HelloPrxCallback callback, int no, String name);

	 void async_hello(@TarsCallback HelloPrxCallback callback, int no, String name, @TarsContext java.util.Map<String, String> ctx);

	 String login(String username, String password);

	CompletableFuture<String>  promise_login(String username, String password);

	 String login(String username, String password, @TarsContext java.util.Map<String, String> ctx);

	 void async_login(@TarsCallback HelloPrxCallback callback, String username, String password);

	 void async_login(@TarsCallback HelloPrxCallback callback, String username, String password, @TarsContext java.util.Map<String, String> ctx);
}
