// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.client.testapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;
import java.util.concurrent.CompletableFuture;

@Servant
public interface PostPrx {

	 String getAuthorPost(int author);

	CompletableFuture<String>  promise_getAuthorPost(int author);

	 String getAuthorPost(int author, @TarsContext java.util.Map<String, String> ctx);

	 void async_getAuthorPost(@TarsCallback PostPrxCallback callback, int author);

	 void async_getAuthorPost(@TarsCallback PostPrxCallback callback, int author, @TarsContext java.util.Map<String, String> ctx);
}
