// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.techcircle.client.app;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class LoginPrxCallback extends TarsAbstractCallback {

	public abstract void callback_login(String ret);

}
